### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by jayvdb** [bskinn/stdio-mgr#29]
This library needs Windows CI.  It could be AppVeyor, Azure, and the Travis Windows beta is also worth considering.

My recent thoughts on them at https://github.com/storyscript/storyscript/issues/1037 , but you need to make a decision.  I'm happy to implement whichever you prefer, or wait until you've done it.

**Comment by bskinn** [comment]
Agreed.

I've been generally planning to migrate to Azure ever since the whole #TravisAlums business... now that Hynek and ... Anthony Shaw, I think? ... have their guides made, this seems like a good time for me to learn. `stdio-mgr` is probably a good project for me to learn on, too, since its test suite is so small. 

Heretofore, my Windows "CI" has just been manually running the test suite on our Windows laptop. :-) Due for an upgrade.

Once it's on Azure, might as well add macOS CI, too?

**Comment by jayvdb** [comment]
> Once it's on Azure, might as well add macOS CI, too?

Less necessary, but it should be easy to do with Azure.
